// <auto-generated />
using System;
using Entity.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250802193549_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.Domain.Models.Implements.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Magic")
                        .HasColumnType("int");

                    b.Property<int>("Resistance")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Defense = 134,
                            Force = 155,
                            Health = 186,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/1.png",
                            Magic = 163,
                            Resistance = 113,
                            Speed = 64
                        },
                        new
                        {
                            Id = 2,
                            Defense = 90,
                            Force = 95,
                            Health = 52,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/2.png",
                            Magic = 69,
                            Resistance = 176,
                            Speed = 168
                        },
                        new
                        {
                            Id = 3,
                            Defense = 160,
                            Force = 98,
                            Health = 95,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/3.png",
                            Magic = 199,
                            Resistance = 63,
                            Speed = 133
                        },
                        new
                        {
                            Id = 4,
                            Defense = 132,
                            Force = 123,
                            Health = 133,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/4.png",
                            Magic = 65,
                            Resistance = 115,
                            Speed = 58
                        },
                        new
                        {
                            Id = 5,
                            Defense = 63,
                            Force = 153,
                            Health = 71,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/5.png",
                            Magic = 59,
                            Resistance = 112,
                            Speed = 183
                        },
                        new
                        {
                            Id = 6,
                            Defense = 69,
                            Force = 193,
                            Health = 76,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/6.png",
                            Magic = 140,
                            Resistance = 117,
                            Speed = 154
                        },
                        new
                        {
                            Id = 7,
                            Defense = 120,
                            Force = 76,
                            Health = 179,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/7.png",
                            Magic = 166,
                            Resistance = 70,
                            Speed = 88
                        },
                        new
                        {
                            Id = 8,
                            Defense = 121,
                            Force = 73,
                            Health = 100,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/8.png",
                            Magic = 68,
                            Resistance = 58,
                            Speed = 184
                        },
                        new
                        {
                            Id = 9,
                            Defense = 140,
                            Force = 184,
                            Health = 196,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/9.png",
                            Magic = 64,
                            Resistance = 93,
                            Speed = 96
                        },
                        new
                        {
                            Id = 10,
                            Defense = 99,
                            Force = 177,
                            Health = 149,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/10.png",
                            Magic = 146,
                            Resistance = 72,
                            Speed = 106
                        },
                        new
                        {
                            Id = 11,
                            Defense = 64,
                            Force = 70,
                            Health = 54,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/11.png",
                            Magic = 52,
                            Resistance = 126,
                            Speed = 76
                        },
                        new
                        {
                            Id = 12,
                            Defense = 111,
                            Force = 107,
                            Health = 86,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/12.png",
                            Magic = 197,
                            Resistance = 77,
                            Speed = 146
                        },
                        new
                        {
                            Id = 13,
                            Defense = 122,
                            Force = 136,
                            Health = 59,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/13.png",
                            Magic = 61,
                            Resistance = 183,
                            Speed = 60
                        },
                        new
                        {
                            Id = 14,
                            Defense = 81,
                            Force = 180,
                            Health = 124,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/14.png",
                            Magic = 75,
                            Resistance = 162,
                            Speed = 109
                        },
                        new
                        {
                            Id = 15,
                            Defense = 57,
                            Force = 147,
                            Health = 190,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/15.png",
                            Magic = 126,
                            Resistance = 81,
                            Speed = 130
                        },
                        new
                        {
                            Id = 16,
                            Defense = 73,
                            Force = 100,
                            Health = 64,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/16.png",
                            Magic = 90,
                            Resistance = 121,
                            Speed = 67
                        },
                        new
                        {
                            Id = 17,
                            Defense = 194,
                            Force = 62,
                            Health = 84,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/17.png",
                            Magic = 79,
                            Resistance = 124,
                            Speed = 87
                        },
                        new
                        {
                            Id = 18,
                            Defense = 169,
                            Force = 174,
                            Health = 70,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/18.png",
                            Magic = 116,
                            Resistance = 172,
                            Speed = 69
                        },
                        new
                        {
                            Id = 19,
                            Defense = 95,
                            Force = 163,
                            Health = 80,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/19.png",
                            Magic = 179,
                            Resistance = 178,
                            Speed = 178
                        },
                        new
                        {
                            Id = 20,
                            Defense = 162,
                            Force = 93,
                            Health = 108,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/20.png",
                            Magic = 128,
                            Resistance = 90,
                            Speed = 108
                        },
                        new
                        {
                            Id = 21,
                            Defense = 125,
                            Force = 57,
                            Health = 199,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/21.png",
                            Magic = 148,
                            Resistance = 177,
                            Speed = 102
                        },
                        new
                        {
                            Id = 22,
                            Defense = 175,
                            Force = 165,
                            Health = 66,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/22.png",
                            Magic = 156,
                            Resistance = 97,
                            Speed = 124
                        },
                        new
                        {
                            Id = 23,
                            Defense = 97,
                            Force = 168,
                            Health = 98,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/23.png",
                            Magic = 122,
                            Resistance = 170,
                            Speed = 169
                        },
                        new
                        {
                            Id = 24,
                            Defense = 187,
                            Force = 117,
                            Health = 182,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/24.png",
                            Magic = 129,
                            Resistance = 54,
                            Speed = 171
                        },
                        new
                        {
                            Id = 25,
                            Defense = 191,
                            Force = 199,
                            Health = 61,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/25.png",
                            Magic = 67,
                            Resistance = 111,
                            Speed = 135
                        },
                        new
                        {
                            Id = 26,
                            Defense = 65,
                            Force = 169,
                            Health = 159,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/26.png",
                            Magic = 87,
                            Resistance = 52,
                            Speed = 195
                        },
                        new
                        {
                            Id = 27,
                            Defense = 158,
                            Force = 134,
                            Health = 173,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/27.png",
                            Magic = 111,
                            Resistance = 158,
                            Speed = 134
                        },
                        new
                        {
                            Id = 28,
                            Defense = 156,
                            Force = 84,
                            Health = 188,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/28.png",
                            Magic = 125,
                            Resistance = 146,
                            Speed = 51
                        },
                        new
                        {
                            Id = 29,
                            Defense = 76,
                            Force = 185,
                            Health = 53,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/29.png",
                            Magic = 164,
                            Resistance = 56,
                            Speed = 187
                        },
                        new
                        {
                            Id = 30,
                            Defense = 186,
                            Force = 87,
                            Health = 83,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/30.png",
                            Magic = 55,
                            Resistance = 174,
                            Speed = 114
                        },
                        new
                        {
                            Id = 31,
                            Defense = 148,
                            Force = 80,
                            Health = 129,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/31.png",
                            Magic = 188,
                            Resistance = 182,
                            Speed = 175
                        },
                        new
                        {
                            Id = 32,
                            Defense = 107,
                            Force = 182,
                            Health = 104,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/32.png",
                            Magic = 105,
                            Resistance = 53,
                            Speed = 198
                        },
                        new
                        {
                            Id = 33,
                            Defense = 166,
                            Force = 157,
                            Health = 74,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/33.png",
                            Magic = 84,
                            Resistance = 175,
                            Speed = 80
                        },
                        new
                        {
                            Id = 34,
                            Defense = 174,
                            Force = 161,
                            Health = 143,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/34.png",
                            Magic = 96,
                            Resistance = 118,
                            Speed = 200
                        },
                        new
                        {
                            Id = 35,
                            Defense = 67,
                            Force = 192,
                            Health = 165,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/35.png",
                            Magic = 57,
                            Resistance = 148,
                            Speed = 71
                        },
                        new
                        {
                            Id = 36,
                            Defense = 188,
                            Force = 124,
                            Health = 150,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/36.png",
                            Magic = 173,
                            Resistance = 133,
                            Speed = 107
                        },
                        new
                        {
                            Id = 37,
                            Defense = 172,
                            Force = 140,
                            Health = 177,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/37.png",
                            Magic = 143,
                            Resistance = 130,
                            Speed = 197
                        },
                        new
                        {
                            Id = 38,
                            Defense = 193,
                            Force = 127,
                            Health = 198,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/38.png",
                            Magic = 196,
                            Resistance = 159,
                            Speed = 173
                        },
                        new
                        {
                            Id = 39,
                            Defense = 79,
                            Force = 59,
                            Health = 69,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/39.png",
                            Magic = 103,
                            Resistance = 163,
                            Speed = 180
                        },
                        new
                        {
                            Id = 40,
                            Defense = 131,
                            Force = 104,
                            Health = 174,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/40.png",
                            Magic = 110,
                            Resistance = 150,
                            Speed = 132
                        },
                        new
                        {
                            Id = 41,
                            Defense = 102,
                            Force = 108,
                            Health = 127,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/41.png",
                            Magic = 62,
                            Resistance = 149,
                            Speed = 125
                        },
                        new
                        {
                            Id = 42,
                            Defense = 51,
                            Force = 128,
                            Health = 72,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/42.png",
                            Magic = 108,
                            Resistance = 59,
                            Speed = 159
                        },
                        new
                        {
                            Id = 43,
                            Defense = 112,
                            Force = 111,
                            Health = 114,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/43.png",
                            Magic = 93,
                            Resistance = 194,
                            Speed = 66
                        },
                        new
                        {
                            Id = 44,
                            Defense = 71,
                            Force = 94,
                            Health = 131,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/44.png",
                            Magic = 177,
                            Resistance = 152,
                            Speed = 112
                        },
                        new
                        {
                            Id = 45,
                            Defense = 127,
                            Force = 53,
                            Health = 88,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/45.png",
                            Magic = 50,
                            Resistance = 138,
                            Speed = 95
                        },
                        new
                        {
                            Id = 46,
                            Defense = 137,
                            Force = 170,
                            Health = 154,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/46.png",
                            Magic = 184,
                            Resistance = 125,
                            Speed = 86
                        },
                        new
                        {
                            Id = 47,
                            Defense = 52,
                            Force = 164,
                            Health = 168,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/47.png",
                            Magic = 70,
                            Resistance = 114,
                            Speed = 103
                        },
                        new
                        {
                            Id = 48,
                            Defense = 159,
                            Force = 109,
                            Health = 62,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/48.png",
                            Magic = 114,
                            Resistance = 191,
                            Speed = 79
                        },
                        new
                        {
                            Id = 49,
                            Defense = 105,
                            Force = 71,
                            Health = 178,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/49.png",
                            Magic = 77,
                            Resistance = 195,
                            Speed = 61
                        },
                        new
                        {
                            Id = 50,
                            Defense = 55,
                            Force = 130,
                            Health = 170,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/50.png",
                            Magic = 134,
                            Resistance = 168,
                            Speed = 72
                        },
                        new
                        {
                            Id = 51,
                            Defense = 185,
                            Force = 175,
                            Health = 117,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/51.png",
                            Magic = 157,
                            Resistance = 139,
                            Speed = 55
                        },
                        new
                        {
                            Id = 52,
                            Defense = 116,
                            Force = 138,
                            Health = 191,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/52.png",
                            Magic = 94,
                            Resistance = 153,
                            Speed = 57
                        },
                        new
                        {
                            Id = 53,
                            Defense = 139,
                            Force = 116,
                            Health = 65,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/53.png",
                            Magic = 85,
                            Resistance = 87,
                            Speed = 105
                        },
                        new
                        {
                            Id = 54,
                            Defense = 181,
                            Force = 181,
                            Health = 169,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/54.png",
                            Magic = 112,
                            Resistance = 109,
                            Speed = 199
                        },
                        new
                        {
                            Id = 55,
                            Defense = 66,
                            Force = 99,
                            Health = 82,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/55.png",
                            Magic = 101,
                            Resistance = 55,
                            Speed = 145
                        },
                        new
                        {
                            Id = 56,
                            Defense = 80,
                            Force = 151,
                            Health = 55,
                            ImageUrl = "https://raw.githubusercontent.com/Leguizamo2502/ImageBootcamp/refs/heads/main/images/56.png",
                            Magic = 155,
                            Resistance = 67,
                            Speed = 182
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("GamePlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GamePlayerId");

                    b.ToTable("Deck");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.GamePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<bool>("Winner")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RoomId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createat")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Card", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Deck", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.GamePlayer", "GamePlayer")
                        .WithMany("Decks")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamePlayer");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.GamePlayer", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.Player", "Player")
                        .WithMany("GamePlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Domain.Models.Implements.Room", "Room")
                        .WithMany("GamePlayers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.GamePlayer", b =>
                {
                    b.Navigation("Decks");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Player", b =>
                {
                    b.Navigation("GamePlayers");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Room", b =>
                {
                    b.Navigation("GamePlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
